[project]
name = "curated-guide"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
    "django-allauth>=65.13.1",
    "django-htmx>=1.26.0",
]
